
name: Deploy Strapi to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            # Update your package list
            #sudo apt update -y

            # Install Node.js and npm
            #sudo apt install nodejs npm -y
            #sudo apt install -y curl
            #curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            #sudo apt-get install nodejs -y
            sudo npm install -g pm2
            cd /home/ubuntu/strapi-deployment

            npm install
            npm run build
            #pm2 restart strapi-project
            pm2 start npm --name strapi-project -- run start
            #pm2 restart strapi-project
            #pm2 restart npm --name strapi-project -- run start
            pm2 save
